//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5
use rocket::serde::{Serialize,Deserialize};
use rbatis::rbdc::datetime::FastDateTime;

#[derive(Clone, Debug,Serialize,Deserialize)]
pub struct SysUser {
    pub user_id: i32,
    pub user_name: String,
    pub password: String,
    pub create_time: Option<FastDateTime>,
    pub update_time: Option<FastDateTime>,
    pub token: Option<String>,
    pub real_name: Option<String>,
    pub avatar: Option<String>,
    pub expire_time: Option<i64>,
}
