//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5
use rocket::serde::{Serialize,Deserialize};
use rbatis::rbdc::datetime::FastDateTime;

#[derive(Clone, Debug,Serialize,Deserialize)]
pub struct SysMenu {
    pub id: i32,
    pub title: Option<String>,
    pub name: Option<String>,
    pub path: String,
    pub component: String,
    pub icon: Option<String>,
    pub permissions: Option<String>,
    pub redirect: Option<String>,
    pub hidden: Option<i8>,
    pub active_menu: Option<String>,
    pub breadcrumb: Option<i8>,
    pub no_cache: Option<i8>,
    pub always_show: Option<i8>,
    pub roles: Option<String>,
    pub query: Option<String>,
    pub create_time: Option<FastDateTime>,
    pub pid: i32,
}
