//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5
use rocket::serde::{Serialize,Deserialize};
use rbatis::rbdc::datetime::FastDateTime;

#[derive(Clone, Debug,Serialize,Deserialize)]
pub struct SysRole {
    pub role_id: i32,
    pub role_name: String,
    pub create_time: FastDateTime,
}
